---
id: Service_Twitter
name: Service_Twitter
full: Twitter client library
description: A client library for the Twitter REST API.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Service_Twitter
authors:
  - name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 3.0.0-RC1
  api: 2.1.0
state:
  release: RC
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^8.1
    composer:
      psr/http-client: ^1.0
      psr/http-factory: ^1.0
      psr/http-message: ^2.0
      horde/oauth: ^4
      horde/controller: ^3
      horde/exception: ^3
      horde/http: ^3
      horde/url: ^3
      horde/util: ^3
keywords:
  - x.com
  - twitter
  - posts
vendor: horde
quality:
  phpstan:
    level: 6
ci-platform:
  '8.1':
    - php: ^8.1
    - ext-dom
    - ext-hash
    - ext-json
    - ext-openssl
  '8.2':
    - php: ^8.1
    - ext-dom
    - ext-hash
    - ext-json
    - ext-openssl
  '8.3':
    - php: ^8.1
    - ext-dom
    - ext-hash
    - ext-json
    - ext-openssl
  '8.4':
    - php: ^8.1
    - ext-dom
    - ext-hash
    - ext-json
    - ext-openssl
  '8.5':
    - php: ^8.1
    - ext-dom
    - ext-hash
    - ext-json
    - ext-openssl
  '8.6':
    - php: ^8.1
    - ext-dom
    - ext-hash
    - ext-json
    - ext-openssl
ci-platform-flags:
  needs_installer_plugin: false
