---
id: Service_Twitter
name: Service_Twitter
full: Twitter client library
description: A client library for the Twitter REST API.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Service_Twitter
authors:
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 3.0.0alpha2
  api: 2.1.0
state:
  release: alpha
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/controller: ^3
      horde/exception: ^3
      horde/http: ^3
      horde/oauth: ^3
      horde/url: ^3
      horde/util: ^3
